#!/usr/bin/env ruby
require "open-uri"

TIME = Time.now
CONF = File.dirname(__FILE__) + "/.emacs.d/"

def download_file(url, name = nil)
  data = open(url).read
  fname = name || url.split("/").last
  File.open(CONF + "vendor/#{fname}", "w") { |f| f.write(data) }
end

def update(pkg, url)
  print "Starting #{pkg} update..."

  if url =~ /git:/
  else
    result = download_file(url)
  end
  puts "DONE"
end



update "CoffeeScript", "https://github.com/nofxx/coffee-mode/raw/master/coffee-mode.el"
update "Rspec Mode", "https://github.com/pezra/rspec-mode/raw/master/rspec-mode.el"
update "HAML Mode", "https://github.com/nex3/haml-mode/raw/master/haml-mode.el"
update "SASS Mode", "https://github.com/nex3/sass-mode/raw/master/sass-mode.el"
update "Linum.el", "http://stud1.tuwien.ac.at/~e0225855/linum/linum.el"
update "Textile", "https://github.com/emacsmirror/textile-mode/raw/master/textile-mode.el"
update "Markdown", "https://github.com/defunkt/markdown-mode/raw/master/markdown-mode.el"
# update "CSS Mode", "http://www.emacswiki.org/emacs/download/css-mode.el"
